services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pali
      POSTGRES_PASSWORD: pali_dev
      POSTGRES_DB: pali_ceramics
    volumes:
      - pali_pg_data:/var/lib/postgresql/data

volumes:
  pali_pg_data:
